import MainProvider from "@/components/providers";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oleksii Bortnytskyi | Folio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={montserrat.className} suppressHydrationWarning={true}>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
